/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : lrm_info.inc
* Description : including the LRM module all header files.
* Author: Xueping.Chen
* Date: 2016-11-26
******************************************************************************/

/* check of multiple include */
#ifndef _LRM_INFO_INC_

#define _LRM_INFO_INC_


/* Files for including */
#include "dio_public.h"
#include "r_tick_api.h"
#include "public.h"
#include "iom_public.h"

#include "yd_typedefs.h"
#include "led_public.h"

#include "lrm_public.h"
#include "lrm_private.h"
#include "lrm_cfg.h"


#endif /*_LRM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-11-26      Initial
*
*===========================================================================*/