/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : rst_info.inc
* Description : including rst module all header files
* Author: Hejianjun
* Date: 2016-12-05
******************************************************************************/

/* check of multiple include */
#ifndef _RST_INFO_INC_

#define _RST_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "rstc_public.h"
#include "rst_public.h"
#include "rst_private.h"
#include "rst_cfg.h"

#endif /*_RST_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        Hejianjun        2016-12-05      Initial
*
*===========================================================================*/