/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : com_info.inc
* Description :including com module all header files.
* Author:Yingying.Liu
* Date: 2016-12-12
******************************************************************************/

/* check of multiple include */
#ifndef _COM_INFO_INC_

#define _COM_INFO_INC_
#include "yd_typedefs.h"
#include "public.h"
#include "v_nwm.h"
#include "nwm_core.h"

#include "public.h"
#include "bat_public.h"
#include "ssb_public.h"
#include "pwr_public.h"
#include "iom_public.h"

#include "st_public.h"
#include "stbc_public.h"

#include "acc_public.h"

#include "com_cfg.h"
#include "com_private.h"
#include "com_public.h"
#endif /*_COM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:            Date:             Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Yingying.Liu         2016-12-12           Initial
*
*===========================================================================*/






