/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : rstc_info.inc
* Description :includes head files.
* Author: Qinhui.Shen
* Date: 2016-12-14
******************************************************************************/

/* check of multiple include */
#ifndef _RSTC_INFO_INC_

#define _RSTC_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "rstc_cfg.h"
#include "rstc_private.h"
#include "rstc_public.h"

#endif /* _RSTC_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-12-14      Initial
*
*===========================================================================*/

