/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : dspi_info.inc
* Description : including DSPI driver header files.
* Author: Qinhui.Shen
* Date: 2016-12-04
******************************************************************************/

/* check of multiple include */
#ifndef _DSPI_INFO_INC_

#define _DSPI_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "dspi_cfg.h"
#include "dspi_private.h"
#include "dspi_public.h"

#endif /* _DSPI_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-12-04      Initial
*
*===========================================================================*/

