/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : bat_info.inc
* Description : including bat module all header files
* Author: zxx
* Date: 2017-6-28
******************************************************************************/

/* check of multiple include */
#ifndef _BAT_INFO_INC_

#define _BAT_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "adm_public.h"
#include "dm_public.h"
#include "nwd_public.h"
#include "v_hand.h"
#include "com_public.h"

#include "bat_public.h"
#include "bat_private.h"
#include "bat_cfg.h"
#endif /*_BAT_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        Hejianjun        2016-12-05      Initial
* V2.0 	      ZXX 	       2017-6-28	
*===========================================================================*/