/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : ostm_info.inc
* Description : including ostm module all header files
* Author: Xiaojie.Zheng
* Date: 2016-12-12
******************************************************************************/

/* check of multiple include */
#ifndef _OSTM_INFO_INC_
#define _OSTM_INFO_INC_


/* Files for including */

#include "Yd_typedefs.h"
#include "device.h"
#include "public.h"
#include "bat_public.h"
#include "com_public.h"
#include "ass_public.h"
#include "ssb_public.h"
#include "chm_public.h"
#include "msg_public.h"
#include "hsd_public.h"
#include "pwr_public.h"
#include "crus_public.h"
#include "tip_public.h"
#include "wfm_public.h"
#include "tpms_public.h"
#include "st_public.h"
#include "scs_public.h"
#include "acc_public.h"
#include "odo_public.h"
#include "rtc_public.h"

#include "dio_public.h"
#include "ism_public.h"
#include "bpm_public.h"
#include "iom_public.h"
#include "stsmg_public.h"
#include "sys_public.h"
#include "nwd_public.h"
#include "stsmg_public.h"

#include "ostm_public.h"
#include "ostm_private.h"
#include "ostm_cfg.h"

#endif /*_OSTM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Xiaojie.Zheng     2016-12-12      Initial
*
*===========================================================================*/
