/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : taub_info.inc
* Description : including taub module all header files
* Author: Xiaojie.Zheng
* Date: 2016-12-12
******************************************************************************/

/* check of multiple include */
#ifndef _TAUB_INFO_INC_
#define _TAUB_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "device.h"
#include "taub_public.h"
#include "taub_private.h"
#include "taub_cfg.h"

#endif /*_TAUB_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Xiaojie.Zheng     2016-12-12      Initial
*
*===========================================================================*/