/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : pwm_info.inc
* Description :including pwm module all header files.
* Author: Xueping.Chen
* Date: 2016-12-13
******************************************************************************/

/* check of multiple include */
#ifndef _PWM_INFO_INC_

#define _PWM_INFO_INC_


/* Files for including */
#include "device.h"
#include "pwm_cfg.h"
#include "pwm_private.h"
#include "pwm_public.h"
#include "yd_typedefs.h"


#endif /*_PWM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-12-13      Initial
*
*===========================================================================*/