/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : bpm_info.inc
* Description :including bpm module all header files.
* Author: Xueping.Chen
* Date: 2016-11-30
******************************************************************************/

/* check of multiple include */
#ifndef _BPM_INFO_INC_

#define _BPM_INFO_INC_


/* Files for including */
#include "ostm_public.h"


#include "taub_public.h"
#include "dio_public.h"
#include "iom_public.h"
#include "stsmg_public.h"

#include "bpm_cfg.h"
#include "bpm_private.h"
#include "bpm_public.h"
#include "yd_typedefs.h"



#endif /*_BPM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-11-30      Initial
*
*===========================================================================*/
