/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : pwr_info.inc
* Description :including pwr module all header files.
* Author: Xueping.Chen
* Date: 2016-12-09
******************************************************************************/

/* check of multiple include */
#ifndef _PWR_INFO_INC_

#define _PWR_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "public.h"
#include "nvm_public.h"
#include "ssb_public.h"
#include "acc_public.h"
#include "com_public.h" 

#include "ism_public.h"


#include "diag_public.h"
#include "nwd_public.h"
#include "st_public.h"
#include "hsd_public.h"
#include "pwr_cfg.h"
#include "pwr_private.h"
#include "pwr_public.h"

#endif /*_PWR_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:                 Userid:                Date:                Description
*--------    ----------       ---------       ------------------------------
*
* V1.0          Xueping.Chen           2016-12-09           Initial
*
*===========================================================================*/
