/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : ssb_info.inc
* Description : including ssb module all header files
* Author: Hejianjun
* Date: 2016-12-03
******************************************************************************/

/* check of multiple include */
#ifndef _FTR_INFO_INC_
#define _FTR_INFO_INC_


/* Files for including */


#include "yd_typedefs.h"
#include "public.h"
#include "pwr_public.h"
#include "bat_public.h"
#include "crus_public.h"
#include "odo_public.h"
#include "slf_public.h"
#include "ssb_public.h"
#include "nwd_public.h"
#include "tip_public.h"
#include "bat_public.h"
#include "diag_public.h"
#include "com_public.h"
#include "adm_public.h"
#include "nvm_public.h"
#include "eed_public.h"


#include "s_fm_api.h"
#include "s_fm_config.h"

#include "wfm_public.h"
#include "ftr_public.h"
#include "ftr_private.h"
#include "ftr_cfg.h"


#endif /*_FTR_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V2.0           CSM              2017-07-04           INITIAL
*
*===========================================================================*/
