/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : crus_info.inc
* Description : including crus module all header files
* Author: ChenSongMing
* Date: 2017-6-29
******************************************************************************/

/* check of multiple include */
#ifndef _CRUS_INFO_INC_

#define _CRUS_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"           /*  add  v_hand.h  for net siganl */


#include "iom_public.h"
#include "adm_public.h"
#include "com_public.h"
#include "pwr_public.h"
#include "bat_public.h"
#include "diag_public.h"
#include "evt_public.h"

#include "crus_public.h"
#include "crus_private.h"
#include "crus_cfg.h"
#endif /*_CRUS_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        Hejianjun        2016-11-30      Initial
* V2.0	      ChenSongMing	2017-6-29
*============================*/