/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : chm_info.inc
* Description :
* Author: xs
* Date: 2017-06-25
******************************************************************************/

/* check of multiple include */
#ifndef _CHM_INFO_INC_
#define _CHM_INFO_INC_


/* Files for including */
#include "Yd_typedefs.h"
#include "public.h"

#include "dio_public.h"
#include "stsmgmsgPriyTab.h"
#include "stsmgwarnPriyTab.h"
#include "pwr_public.h"
#include "com_public.h"
#include "evt_public.h"
#include "stsmg_public.h"
#include "msg_public.h"

#include "r_tick_api.h"
#include "diag_public.h"
#include "illu_public.h"
#include "led_public.h"

#include "chm_public.h"
#include "chm_private.h"
#include "chm_cfg.h"

#endif /*_CHM_INFO_INC_*/
/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                date:                      description
*-----               -----                                 -----------                  -----------
*Rev 1                 xs                                   2017-06-25                  initial
============================================================================================================*/


