/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : com_info.inc
* Description :including com module all header files.
* Author:Yingying.Liu
* Date: 2017-07-06
******************************************************************************/

/* check of multiple include */
#ifndef _NWD_INFO_INC_

#define _NWD_INFO_INC_
#include "yd_typedefs.h"
#include "r_tick_api.h"
#include "public.h"
#include "v_nwm.h"
#include "nwm_core.h"
#include "public.h"
#include "pwr_public.h"

#include "st_public.h"
#include "com_public.h"

#include "nwd_cfg.h"
#include "nwd_private.h"
#include "nwd_public.h"

#endif /*_NWD_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:            Date:             Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       huangyifan         2017-07-06           Initial
* V2.0       huangyifan         2017-07-06           modify
*===========================================================================*/






