/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : idle_info.inc
* Description : including idle module all header files
* Author: Xuenian.Feng
* Date: 2016-12-8
******************************************************************************/
/* check of multiple include */
#ifndef _IDLE_INFO_INC_

#define _IDLE_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include"wdt_public.h"
#include "idle_public.h"
#include "idle_private.h"
#include "idle_cfg.h"



#endif /*_eed_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:                 Userid:                  Date:                          Description
*--------    ----------       ---------       ------------------------------
*
* V1.0            Xuenian.Feng         2016-12-8                         Initial
*
*===========================================================================*/