/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : clock_info.inc
* Description :
* Author: Qinhui.Shen
* Date: 2016-12-13
******************************************************************************/

/* check of multiple include */
#ifndef _CLOCK_INFO_INC_

#define _CLOCK_INFO_INC_

/* Files for including */
#include "public.h"
#include "yd_typedefs.h"
#include "device.h"
#include "clock_cfg.h"
#include "clock_private.h"
#include "clock_public.h"

#endif /* _CLOCK_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-12-13      Initial
*
*===========================================================================*/

