/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : pwmm_info.inc
* Description :including pwmm module all header files.
* Author: Xueping.Chen
* Date: 2016-11-29
******************************************************************************/

/* check of multiple include */
#ifndef _PWMM_INFO_INC_

#define _PWMM_INFO_INC_


/* Files for including */
#include "pwm_public.h"
#include "taub_public.h"
#include "pwmm_cfg.h"
#include "pwmm_private.h"
#include "pwmm_public.h"
#include "yd_typedefs.h"



#endif /*_PWMM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-11-29      Initial
*
*===========================================================================*/