/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : hsd_info.inc
* Description : including hsd module all header files
* Author: Hejianjun
* Date: 2016-12-03
******************************************************************************/

/* check of multiple include */
#ifndef _HSD_INFO_INC_

#define _HSD_INFO_INC_

/* Files for including */

#include "yd_typedefs.h"
#include "public.h"
#include "nvm_public.h"
#include "iom_public.h"
#include "com_public.h" 

#include "adm_public.h"
#include "pwr_public.h"
#include "hsd_public.h"
#include "hsd_private.h"
#include "hsd_cfg.h"


#endif /*_HSD_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.2       Hejianjun        2016-12-03      Initial
*
*===========================================================================*/