/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : eed_info.inc
* Description : including eed module all header files
* Author: Xuenian.Feng
* Date: 2016-11-29
******************************************************************************/
/* check of multiple include */
#ifndef _EED_INFO_INC_

#define _EED_INFO_INC_


/* Files for including */
#include "wdt_public.h"
#include "dspi_public.h"
#include "eed_public.h"
#include "eed_private.h"
#include "eed_cfg.h"
#include "yd_typedefs.h"


#endif /*_eed_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xuenian.Feng      2016-11-29      Initial
*
*===========================================================================*/
