/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : slf_info.inc
* Description :
* Author: zhangxianxiang
* Date: 2017-06-22
******************************************************************************/

/* check of multiple include */
#ifndef _SLF_INFO_INC_
#define _SLF_INFO_INC_


/* Files for including */
#include "Yd_typedefs.h"
#include "adm_public.h"
#include "evt_public.h"

#include "slf_public.h"
#include "slf_private.h"
#include "slf_cfg.h"


#endif /*_SLF_INFO_INC_*/




/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                date:                      description
*-----               -----                                 -----------                  -----------
*Rev 1               zhangxianxiang                     2017-06-22                  init
============================================================================================================*/

