/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : sys_info.inc
* Description :including sys module all header files.
* Author:Liuyingying
* Date: 2017-6-30
******************************************************************************/

/* check of multiple include */
#ifndef _SYS_INFO_INC_

#define _SYS_INFO_INC_
#include "yd_typedefs.h"
#include "public.h"
#include "clock_public.h"
#include "dio_public.h"
#include "interrupt_public.h"
#include "adce_public.h"
#include "ostm_public.h"
#include "pwm_public.h"
#include "rstc_public.h"
#include "rtca_public.h"
#include "stbc_public.h"
#include "taub_public.h"
#include "wdt_public.h"
#include "dspi_public.h"
#include "ism_public.h"
#include "nzm_public.h"

#include "iom_public.h"
#include "adm_public.h"
#include "pwmm_public.h"

#include "bpm_public.h"
#include "lrm_public.h"
#include "mom_public.h"

#include "eed_public.h"
#include "stsmg_public.h"
#include "crus_public.h"
#include "trip_public.h"

#include "st_public.h"
#include "pwr_public.h"
#include "tip_public.h"
#include "odo_public.h"
#include "acc_public.h"
#include "rtc_public.h"
#include "illu_public.h"
#include "ssb_public.h"
#include "ass_public.h"
#include "scs_public.h"
#include "led_public.h"
#include "msg_public.h"
#include "idle_public.h"
#include "nwd_public.h"
#include "com_public.h"
#include "nvm_public.h"
#include "bat_public.h"
#include "avgFuelCsump_V2.h"
#include "RangeToEmptyAlgorithm_V2.h"
#include "FuelLevelAlgorithm_V2.h"
#include "hsd_public.h"
#include "rst_public.h"

#include "evt_public.h"
#include "wfm_public.h"
#include "dm_public.h"
#include "slf_public.h"
#include "tpms_public.h"
#include "ftr_public.h"
#include "nwd_public.h"
#include "chm_public.h"
#include "diag_public.h"


#include "sys_cfg.h"
#include "sys_private.h"
#include "sys_public.h"




#endif /*_SYS_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:            Date:             Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Jianjun.He         2016-12-09           Initial
* V2.0       Liuyingying        2017-6-30            modify
*===========================================================================*/
