/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : led_info.inc
* Description :
* Author: liuyingying
* Date: 2016-11-25
******************************************************************************/

/* check of multiple include */
#ifndef _LED_INFO_INC_
#define _LED_INFO_INC_


/* Files for including */
#include "Yd_typedefs.h"
#include "public.h"
#include "iom_public.h"
#include "lrm_public.h"
#include "nvm_public.h"
#include "pwr_public.h"
#include "stsmg_public.h"
#include "com_public.h"

#include "r_tick_api.h"
#include "evt_public.h"
#include "diag_public.h"
#include "wfm_public.h"
#include "illu_public.h"
#include "nwd_public.h"

#include "led_public.h"
#include "led_private.h"
#include "led_cfg.h"
#endif /*_IOM_INFO_INC_*/




/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                date:                      description
*-----               -----                                 -----------                  -----------
*Rev 1               liuyingying                           2016-11-24                   initial
============================================================================================================*/
