/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : stbc_info.inc
* Description :includes head files.
* Author: Qinhui.Shen
* Date: 2016-12-14
******************************************************************************/

/* check of multiple include */
#ifndef _STBC_INFO_INC_

#define _STBC_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "illu_public.h"
#include "pwm_public.h"
#include "pwmm_public.h"
#include "iom_public.h"
#include "dio_public.h"
#include "bpm_public.h"

#include "r_bsp_gfx_disp_init.h"
#include "stbc_cfg.h"
#include "stbc_private.h"
#include "stbc_public.h"

#endif /* _STBC_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-12-14      Initial
*
*===========================================================================*/

