/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : ssb_info.inc
* Description : including ssb module all header files
* Author: Hejianjun
* Date: 2016-12-03
******************************************************************************/

/* check of multiple include */
#ifndef _SSB_INFO_INC_
#define _SSB_INFO_INC_


/* Files for including */


#include "yd_typedefs.h"
#include "r_tick_api.h"
#include "public.h"
#include "ostm_public.h"
#include "diag_public.h"
#include "com_public.h"
#include "adm_public.h"

#include "ssb_public.h"
#include "ssb_private.h"
#include "ssb_cfg.h"


#endif /*_SSB_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.2       Hejianjun        2016-12-03      Initial
*
*===========================================================================*/