/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : led_info.inc
* Description :
* Author: xs
* Date: 2017-06-23
******************************************************************************/

/* check of multiple include */
#ifndef _TPMS_INFO_INC_
#define _TPMS_INFO_INC_


/* Files for including */
#include "Yd_typedefs.h"
#include "diag_public.h"
#include "pwr_public.h"
#include "com_public.h"
#include "tpms_public.h"
#include "tpms_private.h"
#include "tpms_cfg.h"
#include "r_tick_api.h"
#include "evt_public.h"
#endif /*_TPMS_INFO_INC_*/




/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                   date:                      description
*-----                 -----                                 -----------                  -----------
*Rev 1                  xs                                    2017-06-23                    initial
============================================================================================================*/

