/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : scs_info.inc
* Description : including scs module all header files
* Author: Hejianjun
* Date: 2016-11-30
******************************************************************************/

/* check of multiple include */
#ifndef _SCS_INFO_INC_

#define _SCS_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"           /*  add  v_hand.h  for net siganl */
//#include "stsmg_public.h"

#include "public.h"
#include "pwr_public.h"
#include "nvm_public.h"
#include "com_public.h"

#include "evt_public.h"
#include "dm_public.h"
#include "diag_public.h"

#include "scs_public.h"
#include "scs_private.h"
#include "scs_cfg.h"

#endif /*_SCS_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        Hejianjun         2016-11-30      Initial
* V2.0        huangyinfan     2017-06-23      modify
*log dm,diag module include
*===========================================================================*/