/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : nvm_info.inc
* Description : including nvm module all header files
* Author: Xuenian.Feng
* Date: 2016-12-1
******************************************************************************/
/* check of multiple include */
#ifndef _NVM_INFO_INC_

#define _NVM_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "eed_public.h"
#include "nvm_public.h"
#include "nvm_private.h"
#include "nvm_cfg.h"
#include "wdt_public.h"
#include "ism_public.h"

#endif /*_nvm_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xuenian.Feng      2016-12-1      Initial
*
*===========================================================================*/