/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : illu_info.inc
* Description : including illu module all header files
* Author: Xueping.Chen
* Date: 2016-12-05
******************************************************************************/

/* check of multiple include */
#ifndef _ILLU_INFO_INC_

#define _ILLU_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "public.h"
#include "nzm_public.h"
#include "iom_public.h"
#include "diag_public.h"
#include "pwmm_public.h"
#include "com_public.h"
#include "pwr_public.h"
#include "msg_public.h"
#include "dm_public.h"
#include "bat_public.h"
#include "nwd_public.h"

#include "illu_public.h"
#include "illu_private.h"
#include "illu_cfg.h"



#endif /*_ILLU_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-12-05      Initial
*
*===========================================================================*/
