/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : ass_info.inc
* Description : including ass module all header files
* Author: Hejianjun
* Date: 2016-12-03
******************************************************************************/

/* check of multiple include */
#ifndef _ASS_INFO_INC_

#define _ASS_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "public.h"
#include "iom_public.h"
#include "com_public.h"
#include "diag_public.h"
#include "stsmg_public.h"
#include "pwr_public.h"
#include "evt_public.h"

#include "ass_public.h"
#include "ass_private.h"
#include "ass_cfg.h"

#endif /*_ASS_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.1        Hejianjun        2016-12-03      Initial
*
*===========================================================================*/