/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : dio_info.inc
* Description : including DIO driver header files.
* Author: Qinhui.Shen
* Date: 2016-10-14
******************************************************************************/

/* check of multiple include */
#ifndef _DIO_INFO_INC_

#define _DIO_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "public.h"
#include "dio_cfg.h"
#include "dio_private.h"
#include "dio_public.h"

#endif /* _DIO_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-10-14      Initial
*
*===========================================================================*/

