/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : interrupt_info.inc
* Description :
* Author: Qinhui.Shen
* Date: 2016-10-14
******************************************************************************/

/* check of multiple include */
#ifndef _INTERRUPT_INFO_INC_

#define _INTERRUPT_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "ostm_public.h"
#include "interrupt_cfg.h"
#include "interrupt_private.h"
#include "interrupt_public.h"

#endif /* _INTERRUPT_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-10-14      Initial
*
*===========================================================================*/

