/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : acc_info.inc
* Description : including acc module all header files
* Author: Xiaojie.Zheng
* Date: 2016-12-06
******************************************************************************/

/* check of multiple include */
#ifndef _ACC_INFO_INC_
#define _ACC_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "public.h"
#include "iom_public.h"
#include "adm_public.h"
#include "pwr_public.h"
#include "com_public.h"
#include "nwd_public.h"
#include "acc_public.h"
#include "acc_private.h"
#include "acc_cfg.h"
#include "nvm_public.h"
#include "diag_public.h"
#include "evt_public.h"
#include "odo_public.h"
#endif /*_ACC_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xiaojie.Zheng    2016-12-06     Initial
*
*===========================================================================*/