/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : mom_info.inc
* Description :including mom module all header files.
* Author: Xueping.Chen
* Date: 2016-12-01
******************************************************************************/

/* check of multiple include */
#ifndef _MOM_INFO_INC_

#define _MOM_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "ism_public.h"

#include "r_tick_api.h"
//#include "r_config_ism.h"
//#include "r_ism_api.h"
#include "mom_cfg.h"
#include "mom_private.h"
#include "mom_public.h"

#include "st_public.h"
#include "wdt_public.h"

#endif /*_MOM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-12-01      Initial
*
*===========================================================================*/
