/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : diag_info.inc
* Description : including adce module all header files
* Author: liuyingying
* Date: 2017-06-20 
******************************************************************************/

/* check of multiple include */
#ifndef _DIAG_INFO_INC_
#define _DIAG_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "public.h"
#include "device.h"
#include "diag_public.h"
#include "diag_private.h"
#include "diag_cfg.h"
#include "nvm_public.h"
#include "crus_public.h"

#include <stdlib.h>
#include<stdio.h>
#include<time.h>
#include "s_dsm_api.h"
#include "s_dsm_cfg.h"
#include "s_tpm.h"
#include "s_fm_app.h"


#endif /*_DIAG_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      liuyingying     2017-06-20     Initial
*
*===========================================================================*/