/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : wfm_info.inc
* Description :
* Author: xs
* Date: 2017-06-21
******************************************************************************/

/* check of multiple include */
#ifndef _WFM_INFO_INC_
#define _WFM_INFO_INC_


/* Files for including */
#include "Yd_typedefs.h"
#include "public.h"

#include "pwr_public.h"
#include "com_public.h"
#include "evt_public.h"
#include "bat_public.h"
#include "nwd_public.h"
#include "wfm_public.h"
#include "wfm_private.h"
#include "wfm_cfg.h"

#include "r_tick_api.h"
#include "diag_public.h"

#endif /*_WFM_INFO_INC_*/
/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                date:                      description
*-----               -----                                 -----------                  -----------
*Rev 1                 xs                                   2017-06-21                  initial
============================================================================================================*/

