/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : stsmg_info.inc
* Description : including STSMG header files.
* Author: Qinhui.Shen
* Date: 2016-10-14
******************************************************************************/

/* check of multiple include */
#ifndef _STSMG_INFO_INC_

#define _STSMG_INFO_INC_

/* Files for including */

#include "yd_typedefs.h"
#include "public.h"
#include "led_public.h"
#include "acc_public.h"
#include "crus_public.h"
#include "ass_public.h"



#include "msg_public.h"

#include "stsmg_cfg.h"
#include "stsmg_private.h"
#include "stsmg_public.h"
#include "bpm_public.h"


#endif /* _STSMG_INFO_INC_ */
/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-11-29      Initial
*
*===========================================================================*/

