/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : trip_info.inc
* Description : including trip module all header files
* Author: Xiaojie.Zheng
* Date: 2016-12-02
******************************************************************************/

/* check of multiple include */
#ifndef _TRIP_INFO_INC_
#define _TRIP_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "r_tick_api.h"
#include "dm_public.h"
#include "ostm_public.h"
#include "adm_public.h"
#include "diag_public.h"
#include "pwr_public.h"
#include "rtca_public.h"
#include "rst_public.h"
#include "nzm_public.h"
#include "trip_public.h"
#include "trip_private.h"
#include "trip_cfg.h"


#endif /*_TRIP_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Xiaojie.Zheng     2016-12-02      Initial
*
*===========================================================================*/
