/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : msg_info.inc
* Description : including msg module all header files
* Author: Yingying.Liu
* Date: 2016-12-2
******************************************************************************/
/* check of multiple include */
#ifndef _MSG_INFO_INC_

#define _MSG_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "public.h"
#include "stsmgmsgPriyTab.h"
#include "pwr_public.h"
#include "stsmg_public.h"
#include "evt_public.h"
#include "chm_public.h"
#include "diag_public.h"
#include "illu_public.h"

#include "msg_public.h"
#include "msg_private.h"
#include "msg_cfg.h"



#endif /*_msg_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Yingying.Liu      2016-12-2      Initial
*
*===========================================================================*/
