/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon MultiMedia co.,LTD. All rights reserved.
*
* File Name : led_info.inc
* Description :
* Author: liuyingying
* Date: 2016-11-25
******************************************************************************/
#ifndef _ISM_INFO_INC_
#define _ISM_INFO_INC_

#include "yd_typedefs.h"
#include "ism_public.h"
#include "ism_private.h"
#include "r_config_ism.h"
#include "r_ism_api.h"
#include "Ostm_public.h"
#include "r_ism_sys.h"
#include "R_tick_api.h"

#endif

/*----------------end of file------------------------*/


/*===========================================================================================================
*  File Revision History (bottom to top:first revision to last revision)
*
*============================================================================================================
*$Log:$
*

*Rev:                 Userid:                                date:                      description
*-----               -----                                 -----------                  -----------
*Rev 1               liuyingying                           2016-11-24                   initial
========================================================================================================*/
