/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : iom_info.inc
* Description : including iom module all header files
* Author: Xueping.Chen
* Date: 2016-11-24
******************************************************************************/

/* check of multiple include */
#ifndef _IOM_INFO_INC_

#define _IOM_INFO_INC_


/* Files for including */
#include "dio_public.h"
#include "iom_public.h"
#include "iom_private.h"
#include "iom_cfg.h"
#include "yd_typedefs.h"


#endif /*_IOM_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-11-24      Initial
*
*===========================================================================*/