/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : tip_info.inc
* Description : including tip module all header files
* Author: Hejianjun
* Date: 2016-11-30
******************************************************************************/

/* check of multiple include */
#ifndef _TIP_INFO_INC_

#define _TIP_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "adm_public.h"
#include "iom_public.h"
#include "bat_public.h"
#include "tip_public.h"
#include "tip_private.h"
#include "tip_cfg.h"
#include "com_public.h"


#endif /*_TIP_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0        Hejianjun        2016-11-30      Initial
*
*===========================================================================*/