/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : adce_info.inc
* Description : including adce module all header files
* Author: Xiaojie.Zheng
* Date: 2016-12-14
******************************************************************************/

/* check of multiple include */
#ifndef _ADCE_INFO_INC_
#define _ADCE_INFO_INC_


/* Files for including */

#include "yd_typedefs.h"
#include "device.h"
#include "adce_public.h"
#include "adce_private.h"
#include "adce_cfg.h"
#endif /*_ADCE_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0      Xiaojie.Zheng     2016-12-14      Initial
*
*===========================================================================*/