/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : rtca_info.inc
* Description :includes head files.
* Author: Qinhui.Shen
* Date: 2016-12-13
******************************************************************************/

/* check of multiple include */
#ifndef _RTCA_INFO_INC_

#define _RTCA_INFO_INC_

/* Files for including */
#include "yd_typedefs.h"
#include "device.h"
#include "rtca_public.h"
#include "rtca_private.h"
#include "rtca_cfg.h"

#endif /* _RTCA_INFO_INC_ */


/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Qinhui.Shen      2016-12-13      Initial
*
*===========================================================================*/

