/*****************************************************************************
* Copyright (C) 2016 ShenZhen Yeedon Media co.,LTD. All rights reserved.
*
* File Name : st_cfg.h
* Description : including st module all header files.
* Author: Xueping.Chen
* Date: 2016-12-06
******************************************************************************/

/* check of multiple include */
#ifndef _ST_INFO_INC_

#define _ST_INFO_INC_


/* Files for including */
#include "yd_typedefs.h"
#include "public.h"


#include "r_tick_api.h"
#include "ism_public.h"

#include "mom_public.h"
#include "nvm_public.h"
#include "diag_public.h"
#include "pwr_public.h"
#include "com_public.h"
#include "nwd_public.h"
#include "rtc_public.h"
#include "odo_public.h"
#include "rst_public.h"
#include "bat_public.h"

#include "st_cfg.h"
#include "st_private.h"
#include "st_public.h"

#endif /*_ST_INFO_INC_*/

/*----------------end of file------------------------*/

/*===========================================================================
* File Revision History(bottom to top:first revision to last revision)
*============================================================================
* $Log:$
*
* Rev:         Userid:           Date:               Description
*--------    ----------       ---------       ------------------------------
*
* V1.0       Xueping.Chen      2016-12-06     Initial
*
*===========================================================================*/