/* (C) Mentor Graphics Corporation */
/* Automatically generated file.   */
/* DO NOT EDIT THIS FILE!          */

#include "volcano.h"
#include "v_hand.h"
#include "v_rscan.h"

#include "v_rlin3.h"

typedef struct {
	v_uint8 dumy;
} v_fmd_descriptor;
typedef struct {
	v_uint8 dumy;
} v_c_ram ;
typedef struct {
	v_uint8 dumy;
} v_imf_descriptor;
typedef struct {
	v_uint8 dumy;
} v_s_descriptor;

struct v_controller_descriptor V_AROM v_controllers[] = {
{
    (v_fmd_handle)0x003f3d4c,
    (struct v_c_ram V_RAM * V_RAM_PM)0xfebf8000,
    (void V_NVRAM * V_NVRAM_PM)0x003f4158,
    (void V_NVRAM * V_NVRAM_PM)0x00000000,
    v_rscan_send_frame,
    v_rscan_send_frames,
    v_rscan_read_frame,
    v_rscan_read_frames,
    v_rscan_tx_pending,
    v_rscan_set_mode,
    v_rscan_rx_interrupt_handler,
    v_rscan_init_controller,
    v_rscan_connect_controller,
    v_rscan_disconnect_controller,
    v_rscan_controller_active,
    v_rscan_controller_ioctl,
    v_rscan_tx_interrupt_handler,
    v_rscan_busoff_interrupt_handler,
    v_rscan_check_frame,
    (void (*)(v_nwm_recdata V_ARAM * V_ARAM_PM))0,
    (void V_RAM * V_RAM_PM)0xfebf80b8,
    (v_uint8)0x01,
    (v_uint8)0x00
},
{
    (v_fmd_handle)0x003f3f9c,
    (struct v_c_ram V_RAM * V_RAM_PM)0xfebf811c,
    (void V_NVRAM * V_NVRAM_PM)0x003f440c,
    (void V_NVRAM * V_NVRAM_PM)0x003f4440,
    v_rlin3_send_frame,
    v_rlin3_send_frames,
    v_rlin3_read_frame,
    v_rlin3_read_frames,
    v_rlin3_tx_pending,
    v_rlin3_set_mode,
    v_rlin3_rx_interrupt_handler,
    v_rlin3_init_controller,
    v_rlin3_connect_controller,
    v_rlin3_disconnect_controller,
    v_rlin3_controller_active,
    v_rlin3_controller_ioctl,
    v_rlin3_tx_interrupt_handler,
    (void (*)(v_c_handle))0,
    v_rlin3_check_frame,
    (void (*)(v_nwm_recdata V_ARAM * V_ARAM_PM))0,
    (void V_RAM * V_RAM_PM)0xfebf81d4,
    (v_uint8)0x04,
    (v_uint8)0x01
},
{	(v_fmd_handle)0,
 	(struct v_c_ram V_RAM * V_RAM_PM)0,
 	(void V_NVRAM * V_NVRAM_PM)0,
 	(void V_NVRAM * V_NVRAM_PM)0,
 	(v_bool (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_c_handle, v_frame_map V_RAM * V_RAM_PM, v_frame_map V_RAM * V_RAM_PM))0,
 	(v_bool (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_c_handle))0,
 	(v_bool (*)(v_c_handle))0,
 	(void (*)(v_c_handle, v_fmd_handle))0,
 	(v_imf_handle (*)(v_c_handle))0,
 	(v_uint8 (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(v_bool (*)(v_c_handle))0,
 	(v_uint16 (*)(v_c_handle, v_ioctl_op, void V_ARAM * V_ARAM_PM))0,
 	(v_imf_handle (*)(v_c_handle))0,
 	(void (*)(v_c_handle))0,
 	(v_uint8 (*)(v_c_handle, void V_NVRAM * V_NVRAM_PM))0,
 	(void (*)(v_nwm_recdata V_ARAM * V_ARAM_PM))0,
 	(void V_RAM * V_RAM_PM)0,
	0,
	0 }
}; /* end v_controllers[] */

v_uint16 V_AROM v_flag_byte_count = 0x0004;
v_uint8 V_ARAM v_flag_buffer[4];

struct v_fl_descriptor V_AROM v_flags[] = {
{
    (v_s_handle)0x003f14ec,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)&v_flags[0],
    (v_imf_handle)0x003f3d0c,
    1,
    (v_bool)1,
},
{
    (v_s_handle)0x003f05e0,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1dc8,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    4,
    (v_bool)1,
},
{
    (v_s_handle)0x003f08f8,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    8,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1da4,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    16,
    (v_bool)1,
},
{
    (v_s_handle)0x003f02ec,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    32,
    (v_bool)1,
},
{
    (v_s_handle)0x003f0b38,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    64,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1af8,
    &v_flag_buffer[0],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    128,
    (v_bool)1,
},
{
    (v_s_handle)0x003f20e0,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    1,
    (v_bool)1,
},
{
    (v_s_handle)0x003f2104,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1414,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    4,
    (v_bool)1,
},
{
    (v_s_handle)0x003f013c,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    8,
    (v_bool)1,
},
{
    (v_s_handle)0x003f0040,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    16,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1da4,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    32,
    (v_bool)1,
},
{
    (v_s_handle)0x003f214c,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    64,
    (v_bool)1,
},
{
    (v_s_handle)0x003f1cf0,
    &v_flag_buffer[1],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    128,
    (v_bool)1,
},
{
    (v_s_handle)0x003f10b4,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    1,
    (v_bool)1,
},
{
    (v_s_handle)0x003f38ec,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1,
},
{
    (v_s_handle)0x003f20bc,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    4,
    (v_bool)1,
},
{
    (v_s_handle)0x003f076c,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    8,
    (v_bool)1,
},
{
    (v_s_handle)0x003f06dc,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)&v_flags[20],
    (v_imf_handle)0x003f3d1c,
    16,
    (v_bool)1,
},
{
    (v_s_handle)0x003f0700,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)&v_flags[21],
    (v_imf_handle)0x003f3d2c,
    32,
    (v_bool)1,
},
{
    (v_s_handle)0x003f145c,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    64,
    (v_bool)1,
},
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_flags[] */


struct v_fl_descriptor V_AROM v_transmit_flags[] = {
{
    (v_s_handle)0x003f25f0,
    &v_flag_buffer[2],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    128,
    (v_bool)1
},
{
    (v_s_handle)0x003f34fc,
    &v_flag_buffer[3],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    1,
    (v_bool)1
},
{
    (v_s_handle)0x003f3784,
    &v_flag_buffer[3],
    (v_fptr)0,
    (struct v_fl_descriptor V_AROM * V_AROM_PM)0,
    (v_imf_handle)0,
    2,
    (v_bool)1
},
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_transmit_flags[] */

v_uint16 V_AROM v_overrun_flag_byte_count = 0x0001;
v_uint8 V_ARAM v_overrun_flag_buffer[1];

struct v_fl_descriptor V_AROM v_overrun_flags[] = {
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM* V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_overrun_flags[] */


struct v_fl_descriptor V_AROM v_timeout_flags[] = {
{	(v_s_handle)0,
	(v_uint8 V_ARAM * V_ARAM_PM)0,
	(v_fptr)0,
	(struct v_fl_descriptor V_AROM * V_AROM_PM)0,
	(v_imf_handle)0,
	0,
	0 }
}; /* end v_timeout_flags[] */

v_bool V_AROM v_use_enhanced_timeouts = 0;
v_uint8 V_ARAM v_ctrl_connected[1];

struct v_t_descriptor V_AROM v_timeouts[] = {
{
    (v_s_handle)0,
    (v_s_handle)0,
    (v_fl_handle)0,
    {
        (v_uint8 V_AROM * V_AROM_PM)0
    },
    (v_uint8 V_ARAM * V_ARAM_PM)0,
    0,
    0,
    (v_uint16 V_ARAM * V_ARAM_PM)0,
    (v_bool)0 }
}; /* end v_timeouts[] */

v_uint16 V_AROM v_imf_not[] = {0xffff,0xffff,0xffff,0x0000,0x0014,0x0015,0xffff,0xffff};
v_uint8 V_AROM v_imf_inot[] = {0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff};
v_imf_handle V_AROM v_imf_array = (v_imf_handle)0x003f3cdc;
v_uint32 V_AROM v_fixed_checksum = 0x86d32000;
v_uint32 V_AROM v_target_checksum = 0xf847ad75;
